#!/bin/bash

dir="$(ruby -e "puts File.expand_path('../..', File.realpath('$0'))")"
export PATH="/usr/local/bin:$PATH"
/opt/homebrew/bin/shadowenv exec --dir "$dir" -- "$dir/exe/github_notifier" "$@"
